trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - main
      - release/*
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - README.md

variables:
  - template: variables.yml

resources:
  repositories:
    - repository: templates
      type: github
      name: decentralized-cloud/templates
      endpoint: decentralized-cloud

name: $(GitVersion.SemVer)

stages:
  - stage: Build
    jobs:
      - template: build/build-test-publish.yml@templates
        parameters:
          version: ${{ variables.artifactVersion }}
          vmImage: ${{ variables.linuxVmImage }}
          shouldBuildContract: false
          shouldPublishServiceDockerImage: true
          shouldTestPublishResult: true
          shouldPublishHelmChartAsArtifact: true
          shouldPublishHelmChart: ${{ variables.shouldPublishHelmChart }}
          shouldPublishFirebaseAsArtifact: true
          dockerContainerRegistry: ${{ variables.dockerContainerRegistry }}
          dockerRepositoryName: ${{ variables.dockerRepositoryName }}
          dockerBuildFilePath: ${{ variables.dockerBuildFilePath }}
          dockerBuildContext: ${{ variables.dockerBuildContext }}
          testDockerComposeFilePath: ${{ variables.testDockerComposeFilePath }}
          coverallsServiceName: ${{ variables.coverallsServiceName }}
          coverallsRepoToken: ${{ variables.coverallsRepoToken }}
          helmChartsDirectoryPath: ${{ variables.helmChartsDirectoryPath }}
          helmChartsOutputDirectoryPath: ${{ variables.helmChartsOutputDirectoryPath }}
          helmArtifactName: ${{ variables.helmArtifactName }}
          buildAndPushHelmChartDockerFilePath: ${{ variables.buildAndPushHelmChartDockerFilePath }}
          buildAndPushHelmChartDockerBuildContext: ${{ variables.buildAndPushHelmChartDockerBuildContext }}
          githubAccessCredentials: ${{ variables.githubAccessCredentials }}
          firbaseArtifactName: ${{ variables.firbaseArtifactName }}

  - stage: Dev
    dependsOn: [Build]
    jobs:
      - template: release/deploy-hosting-firebase.yml@templates
        parameters:
          environment: Dev
          vmImage: ${{ variables.linuxVmImage }}
          artifactName: ${{ variables.firbaseArtifactName }}
          token:  ${{ variables.firebaseToken }}
          projectId:  ${{ variables.firebaseProjectId }}
          resourceName:  ${{ variables.devFirbaseResourceName }}
          extraArguments:  "--build-arg API_GATEWAY_PUBLIC_URL=$(API_GATEWAY_PUBLIC_URL_DEV) --build-arg AUTH0_DOMAIN=$AUTH0_DOMAIN --build-arg AUTH0_CLIENT_ID=$(AUTH0_CLIENT_ID_DEV) --build-arg GOOGLE_MAP_API_KEY=$(GOOGLE_MAP_API_KEY_DEV) --build-arg IPINFO_ACCESS_TOKEN=$(IPINFO_ACCESS_TOKEN_DEV)"

  - stage: Test
    dependsOn: [Dev]
    jobs:
      - template: release/deploy-hosting-firebase.yml@templates
        parameters:
          environment: Test
          vmImage: ${{ variables.linuxVmImage }}
          artifactName: ${{ variables.firbaseArtifactName }}
          token:  ${{ variables.firebaseToken }}
          projectId:  ${{ variables.firebaseProjectId }}
          resourceName:  ${{ variables.testFirbaseResourceName }}
          extraArguments:  "--build-arg API_GATEWAY_PUBLIC_URL=$(API_GATEWAY_PUBLIC_URL_TEST) --build-arg AUTH0_DOMAIN=$AUTH0_DOMAIN --build-arg AUTH0_CLIENT_ID=$(AUTH0_CLIENT_ID_TEST) --build-arg GOOGLE_MAP_API_KEY=$(GOOGLE_MAP_API_KEY_TEST) --build-arg IPINFO_ACCESS_TOKEN=$(IPINFO_ACCESS_TOKEN_TEST)"

  - stage: Prod
    dependsOn: [Test]
    jobs:
      - template: release/deploy-hosting-firebase.yml@templates
        parameters:
          environment: Prod
          vmImage: ${{ variables.linuxVmImage }}
          artifactName: ${{ variables.firbaseArtifactName }}
          token:  ${{ variables.firebaseToken }}
          projectId:  ${{ variables.firebaseProjectId }}
          resourceName:  ${{ variables.prodFirbaseResourceName }}
          extraArguments:  "--build-arg API_GATEWAY_PUBLIC_URL=$(API_GATEWAY_PUBLIC_URL_PROD) --build-arg AUTH0_DOMAIN=$AUTH0_DOMAIN --build-arg AUTH0_CLIENT_ID=$(AUTH0_CLIENT_ID_PROD) --build-arg GOOGLE_MAP_API_KEY=$(GOOGLE_MAP_API_KEY_PROD) --build-arg IPINFO_ACCESS_TOKEN=$(IPINFO_ACCESS_TOKEN_PROD)"
